ALTER TABLE sales
  ADD COLUMN IF NOT EXISTS vat_enabled   BOOLEAN      NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS vat_amount    NUMERIC(14,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS report_amount NUMERIC(14,2) NOT NULL DEFAULT 0;