import { z } from "zod";
import { Router } from "express";
import { query, withTx } from "../../config/db.js";
import { requireAuth } from "../../middleware/auth.js";
import { requirePermission } from "../../middleware/rbac.js";
import { audit } from "../../utils/audit.js";
import { notFound, conflict } from "../../utils/errors.js";

const router = Router();
router.use(requireAuth);

/* -------------------------------------------------------------------------- */
/* Rounding helpers                                                           */
/* -------------------------------------------------------------------------- */
const round2 = (n) => Math.round((Number(n) || 0) * 100) / 100;
const round3 = (n) => Math.round((Number(n) || 0) * 1000) / 1000;

/* --------------------------------------------------------------------------
   Schema for a single purchase row.

   Money rule:
     net_qty = gross_qty         (dust is a report-only figure)
     total   = net_qty × rate

   Trip rule:
     Every line in one batch shares the same `trip_id` (a UUID generated by
     the client) and the same `truck_no`. `trip_id` may be null for
     single-row creates.
   -------------------------------------------------------------------------- */
const lineSchema = z.object({
  invoice:             z.string().min(1).max(60),
  supplier_id:         z.number().int().positive(),
  material:            z.string().min(1).max(120),

  date_bs_year:        z.number().int().min(2000).max(2200),
  date_bs_month:       z.number().int().min(1).max(12),
  date_bs_day:         z.number().int().min(1).max(32),
  date_ad:             z.string(),

  gross_qty:           z.number().min(0),
  dust_qty:            z.number().min(0).optional(),
  net_qty:             z.number().min(0).optional(),   // ignored — recomputed
  rate:                z.number().min(0),
  total:               z.number().min(0).optional(),   // ignored — recomputed

  // Trip metadata
  trip_id:             z.string().uuid().nullable().optional(),
  truck_no:            z.string().max(60).nullable().optional(),

  // Truck & transport legacy fields (kept so single-row POST still works)
  truck_weight_kg:     z.number().min(0).nullable().optional(),
  truck_driver:        z.string().max(120).optional(),
  truck_driver_phone:  z.string().max(40).optional(),
  contact_person:      z.string().max(120).optional(),
  contact_phone:       z.string().max(40).optional(),
  from_location:       z.string().max(200).optional(),
  to_location:         z.string().max(200).optional(),
  loader_name:         z.string().max(120).optional(),

  transport_fee:       z.number().min(0).optional(),
  labor_charge:        z.number().min(0).optional(),
  road_expense:        z.number().min(0).optional(),
  tax_gbse:            z.number().min(0).optional(),

  // Payment (optional) — logged as a transaction when amount_paid > 0
  amount_paid:         z.number().min(0).optional(),
  payment_method:      z.enum(["Cash", "Online"]).optional(),
  cash_source:         z.string().max(120).optional(),
  paid_by:             z.string().max(120).optional(),
  signature:           z.string().max(120).optional(),

  status:              z.enum(["Delivered", "Pending"]).optional(),
  company:             z.string().max(120).optional(),
});

const batchSchema = z.object({
  lines: z.array(lineSchema).min(1).max(50),
});

/* --------------------------------------------------------------------------
   Recompute net_qty and total from the raw inputs.
   Dust is report-only: net = gross, total = gross × rate.
   -------------------------------------------------------------------------- */
function recompute(input) {
  const gross = Number(input.gross_qty) || 0;
  const rate  = Number(input.rate)      || 0;
  input.net_qty = round3(Math.max(0, gross));
  input.total   = round2(input.net_qty * rate);
}

/* --------------------------------------------------------------------------
   Shared INSERT logic — used by both the single-row POST and the batch POST.
   Runs inside a transaction provided by the caller.
   -------------------------------------------------------------------------- */
async function insertPurchase(client, input, userId) {
  const {
    amount_paid, payment_method, cash_source, paid_by, signature,
    ...purchaseFields
  } = input;

  const cols = Object.keys(purchaseFields);
  const vals = Object.values(purchaseFields);
  cols.push("created_by");
  vals.push(userId);

  if (cash_source) { cols.push("cash_source"); vals.push(cash_source); }
  if (paid_by)     { cols.push("paid_by");     vals.push(paid_by); }
  if (signature)   { cols.push("signature");   vals.push(signature); }

  const placeholders = cols.map((_, i) => `$${i + 1}`);
  const { rows } = await client.query(
    `INSERT INTO purchases (${cols.join(",")}) VALUES (${placeholders.join(",")}) RETURNING *`,
    vals
  );
  return { row: rows[0], amount_paid, payment_method };
}

/* ========================================================================== */
/* LIST — every purchase with paid / due rolled up from the ledger.           */
/* ========================================================================== */
router.get("/", requirePermission("purchases", "view"), async (_req, res, next) => {
  try {
    const { rows } = await query(`
      SELECT p.*,
             COALESCE((
               SELECT SUM(CASE WHEN t.direction='out' THEN t.amount ELSE -t.amount END)
                 FROM transactions t
                WHERE t.ref_type = 'purchase'
                  AND t.ref_id   = p.id
                  AND t.deleted_at IS NULL
             ), 0) AS paid_amount
        FROM purchases p
       WHERE p.deleted_at IS NULL
       ORDER BY p.date_ad DESC, p.id DESC
    `);

    const items = rows.map((r) => ({
      ...r,
      paid_amount: Number(r.paid_amount) || 0,
      due_amount: Math.max(0, Number(r.total) - (Number(r.paid_amount) || 0)),
    }));

    res.json({ items });
  } catch (e) { next(e); }
});

/* ========================================================================== */
/* GET ONE                                                                    */
/* ========================================================================== */
router.get("/:id", requirePermission("purchases", "view"), async (req, res, next) => {
  try {
    const { rows } = await query(
      `SELECT * FROM purchases WHERE id = $1 AND deleted_at IS NULL`,
      [req.params.id]
    );
    if (!rows.length) throw notFound();
    res.json({ item: rows[0] });
  } catch (e) { next(e); }
});

/* ========================================================================== */
/* BATCH CREATE — one truck trip with N lines, all-or-nothing.                */
/* Declared BEFORE /:id so "batch" isn't captured as an :id param.            */
/* ========================================================================== */
router.post("/batch", requirePermission("purchases", "create"), async (req, res, next) => {
  try {
    const { lines } = batchSchema.parse(req.body);

    lines.forEach(recompute);

    // Invoices must be unique within the batch and against the DB.
    const invoices = lines.map((l) => l.invoice);
    const seen = new Set();
    for (const inv of invoices) {
      if (seen.has(inv)) throw conflict(`Duplicate invoice in batch: ${inv}`);
      seen.add(inv);
    }
    const dup = await query(
      `SELECT invoice FROM purchases WHERE invoice = ANY($1) AND deleted_at IS NULL`,
      [invoices]
    );
    if (dup.rowCount) {
      throw conflict(`Invoice(s) already exist: ${dup.rows.map((r) => r.invoice).join(", ")}`);
    }

    // Resolve supplier names in one shot for the payment ledger.
    const supplierIds = [...new Set(lines.map((l) => l.supplier_id))];
    const supRows = await query(
      `SELECT id, name FROM suppliers WHERE id = ANY($1) AND deleted_at IS NULL`,
      [supplierIds]
    );
    const supplierNameById = new Map(supRows.rows.map((r) => [r.id, r.name]));

    // Every line must share the same trip_id and truck_no if either is set.
    const tripIds = [...new Set(lines.map((l) => l.trip_id).filter(Boolean))];
    if (tripIds.length > 1) {
      throw conflict("All lines in a batch must share the same trip_id");
    }
    const tripId  = tripIds[0] || null;
    const truckNo = lines[0].truck_no || null;

    const created = await withTx(async (client) => {
      const createdRows = [];

      for (const line of lines) {
        const { row, amount_paid, payment_method } = await insertPurchase(
          client,
          line,
          req.user.id
        );
        createdRows.push({ row, amount_paid, payment_method });
      }

      // ONE linked transportation row for the whole trip. Only created when
      // the trip carries truck info or explicit transport costs.
      const tripSource = {
        ...createdRows[0].row,
        truck_no:      truckNo,
        trip_id:       tripId,
        // Sum gross_qty across all lines as the default load
        net_qty:       createdRows.reduce((s, r) => s + Number(r.row.net_qty || 0), 0),
      };
      await insertLinkedTransportTx(client, tripSource);

      // Payments: one transaction per line.
      for (const { row, amount_paid, payment_method } of createdRows) {
        if (amount_paid !== undefined && amount_paid !== null && Number(amount_paid) >= 0) {
          const supplierName =
            supplierNameById.get(row.supplier_id) || String(row.supplier_id);
          const paidMethod = payment_method || "Cash";
          await client.query(
            `INSERT INTO transactions
               (type, party_type, party_key, party_label, direction, amount, method,
                ref_type, ref_id,
                date_bs_year, date_bs_month, date_bs_day, date_ad,
                company, note, created_by)
             VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16)`,
            [
              "purchase_payment", "supplier",
              supplierName, supplierName,
              "out", Number(amount_paid), paidMethod,
              "purchase", row.id,
              row.date_bs_year, row.date_bs_month, row.date_bs_day, row.date_ad,
              row.company || null,
              "Paid with purchase",
              req.user.id,
            ]
          );
        }
      }

      return createdRows.map((r) => r.row);
    });

    await audit(req, "purchase.create_batch", "purchase_batch", tripId, {
      count: created.length,
      invoices: created.map((r) => r.invoice),
      trip_id: tripId,
      truck_no: truckNo,
    });

    res.status(201).json({ items: created, trip_id: tripId });
  } catch (e) { next(e); }
});

/* ========================================================================== */
/* SINGLE CREATE — kept for the "New Purchase" path and any other caller.     */
/* ========================================================================== */
router.post("/", requirePermission("purchases", "create"), async (req, res, next) => {
  try {
    const input = lineSchema.parse(req.body);
    recompute(input);

    const dup = await query(
      `SELECT 1 FROM purchases WHERE invoice = $1 AND deleted_at IS NULL`,
      [input.invoice]
    );
    if (dup.rowCount) throw conflict("A purchase with that invoice already exists");

    const supplierRow = await query(
      `SELECT name FROM suppliers WHERE id = $1 AND deleted_at IS NULL`,
      [input.supplier_id]
    );
    const supplierName = supplierRow.rows[0]?.name || String(input.supplier_id);

    const { amount_paid, payment_method } = input;

    const created = await withTx(async (client) => {
      const { row } = await insertPurchase(client, input, req.user.id);
      return row;
    });

    // Single-row POST still links a transportation row the old way.
    if (created.truck_no || created.trip_id) {
      try {
        await query(
          `INSERT INTO transportation
             (sale_id, purchase_id, customer_id,
              vehicle, driver, driver_phone, loader,
              from_location, to_location, load_kg,
              fee, advance, labor_charge, road_expense, tax_gbse,
              trip_id,
              date_bs_year, date_bs_month, date_bs_day, date_ad,
              status)
           VALUES (NULL,$1,NULL,$2,NULL,NULL,NULL,NULL,NULL,$3,0,0,0,0,0,$4,$5,$6,$7,$8,$9)`,
          [
            created.id,
            created.truck_no || null,
            Number(created.net_qty) || 0,
            created.trip_id || null,
            created.date_bs_year, created.date_bs_month, created.date_bs_day, created.date_ad,
            created.status === "Pending" ? "In Transit" : "Delivered",
          ]
        );
      } catch (err) {
        console.error("transport link failed for purchase", created.id, err.message);
      }
    }

    let payment = null;
    if (amount_paid !== undefined && amount_paid !== null && Number(amount_paid) >= 0) {
      const paidMethod = payment_method || "Cash";
      const { rows } = await query(
        `INSERT INTO transactions
           (type, party_type, party_key, party_label, direction, amount, method,
            ref_type, ref_id,
            date_bs_year, date_bs_month, date_bs_day, date_ad,
            company, note, created_by)
         VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16)
         RETURNING *`,
        [
          "purchase_payment", "supplier",
          supplierName, supplierName,
          "out", Number(amount_paid), paidMethod,
          "purchase", created.id,
          created.date_bs_year, created.date_bs_month, created.date_bs_day, created.date_ad,
          created.company || null,
          "Paid with purchase",
          req.user.id,
        ]
      );
      payment = rows[0];
    }

    await audit(req, "purchase.create", "purchase", created.id, {
      invoice: created.invoice,
      linkedPayment: payment?.id || null,
    });

    res.status(201).json({ item: created, payment });
  } catch (e) { next(e); }
});

/* ========================================================================== */
/* PATCH — partial update. Recomputes net_qty/total if gross or rate changed. */
/* ========================================================================== */
router.patch("/:id", requirePermission("purchases", "update"), async (req, res, next) => {
  try {
    const input = lineSchema.partial().parse(req.body);
    delete input.amount_paid;
    delete input.payment_method;
    delete input.net_qty;
    delete input.total;

    if (input.gross_qty !== undefined || input.rate !== undefined) {
      const cur = await query(
        `SELECT gross_qty, rate FROM purchases WHERE id = $1 AND deleted_at IS NULL`,
        [req.params.id]
      );
      if (!cur.rowCount) throw notFound();

      const gross = Number(input.gross_qty ?? cur.rows[0].gross_qty) || 0;
      const rate  = Number(input.rate      ?? cur.rows[0].rate)      || 0;

      input.net_qty = round3(Math.max(0, gross));
      input.total   = round2(input.net_qty * rate);
    }

    const entries = Object.entries(input);
    if (!entries.length) return res.json({ ok: true });

    const sets = entries.map(([k], i) => `${k} = $${i + 1}`);
    const vals = entries.map(([, v]) => v);
    sets.push("updated_at = now()");
    vals.push(req.params.id);
    const { rowCount } = await query(
      `UPDATE purchases SET ${sets.join(", ")} WHERE id = $${vals.length} AND deleted_at IS NULL`,
      vals
    );
    if (!rowCount) throw notFound();
    await audit(req, "purchase.update", "purchase", req.params.id, input);
    res.json({ ok: true });
  } catch (e) { next(e); }
});

/* ========================================================================== */
/* DELETE — soft delete the purchase + its own payments. Linked transportation */
/* is only soft-deleted when it links exclusively to this purchase.           */
/* ========================================================================== */
router.delete("/:id", requirePermission("purchases", "delete"), async (req, res, next) => {
  try {
    const { rows } = await query(
      `SELECT trip_id FROM purchases WHERE id = $1 AND deleted_at IS NULL`,
      [req.params.id]
    );
    if (!rows.length) throw notFound();
    const tripId = rows[0].trip_id;

    await query(
      `UPDATE purchases SET deleted_at = now() WHERE id = $1 AND deleted_at IS NULL`,
      [req.params.id]
    );

    // Only delete linked transportation if no other live purchase shares the
    // same trip (or, for legacy rows, no truck sibling remains).
    if (tripId) {
      const { rowCount } = await query(
        `SELECT 1 FROM purchases WHERE trip_id = $1 AND deleted_at IS NULL LIMIT 1`,
        [tripId]
      );
      if (!rowCount) {
        await query(
          `UPDATE transportation SET deleted_at = now()
            WHERE trip_id = $1 AND deleted_at IS NULL`,
          [tripId]
        );
      }
    } else {
      await query(
        `UPDATE transportation SET deleted_at = now()
          WHERE purchase_id = $1 AND deleted_at IS NULL`,
        [req.params.id]
      );
    }

    await query(
      `UPDATE transactions SET deleted_at = now()
        WHERE ref_type = 'purchase' AND ref_id = $1 AND deleted_at IS NULL`,
      [req.params.id]
    );

    await audit(req, "purchase.delete", "purchase", req.params.id);
    res.json({ ok: true });
  } catch (e) { next(e); }
});

/* ==========================================================================
   Local helper — inserts the transportation row for a purchase trip.
   Called once per batch (not per line). No-ops when the trip has no truck
   info and no explicit transport costs.
   ========================================================================== */
async function insertLinkedTransportTx(client, source) {
  const {
    id,
    truck_no,
    trip_id,
    date_bs_year, date_bs_month, date_bs_day, date_ad,
    transport_fee, labor_charge, road_expense, tax_gbse,
    truck_driver, truck_driver_phone,
    from_location, to_location,
    loader_name,
    customer_id,
    net_qty,
    status,
  } = source;

  const fee   = Number(transport_fee) || 0;
  const labor = Number(labor_charge)  || 0;
  const road  = Number(road_expense)  || 0;
  const tax   = Number(tax_gbse)      || 0;
  const totalCost = fee + labor + road + tax;

  const hasData =
    totalCost > 0 ||
    truck_no || truck_driver || truck_driver_phone ||
    from_location || to_location || loader_name;
  if (!hasData) return null;

  const { rows } = await client.query(
    `INSERT INTO transportation
       (sale_id, purchase_id, customer_id,
        vehicle, driver, driver_phone, loader,
        from_location, to_location, load_kg,
        fee, advance, labor_charge, road_expense, tax_gbse,
        trip_id,
        date_bs_year, date_bs_month, date_bs_day, date_ad,
        status)
     VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,
             $11,$12,$13,$14,$15,
             $16,
             $17,$18,$19,$20,
             $21)
     RETURNING *`,
    [
      null, id, customer_id || null,
      truck_no || null,
      truck_driver || null,
      truck_driver_phone || null,
      loader_name || null,
      from_location || null,
      to_location || null,
      Number(net_qty) || 0,
      fee, fee,                        // fee and advance both start equal
      labor, road, tax,
      trip_id || null,
      date_bs_year, date_bs_month, date_bs_day, date_ad,
      status === "Pending" ? "In Transit" : "Delivered",
    ]
  );
  return rows[0];
}

export default router;